---
title: "🌊 `Covert Reef Team Members` 🪸"
format: 
  html:
    mermaid: 
      theme: default
    about:
      template: jolla
      links:
        - href: "https://dreytwy.shinyapps.io/VastChallengeCovertReef/"
          icon: globe
          text: Shiny
          target: _blank
        - href: "https://github.com/JianyiLii/Covert_Reef"
          icon: github
          text: GitHub
          target: _blank
---

:::::: panel-tabset
## Yang Lu

My name is Yang Lu, and I’m currently pursuing a Master at Singapore Management University, specializing in the Financial Technology& Analytics track. 
In this Visual Analytics and Applications course, I focus on harnessing the power of RStudio to transform complex financial datasets into clear, actionable insights. My work includes data wrangling with **tidyverse**, creating interactive visualizations with **ggplot2** and **plotly**, and building dashboards using **shiny**. I am passionate about applying these skills to real-world fintech challenges and continuously learning new tools and techniques to advance my analytical toolkit.


::: {.callout-note title="Yang Lu"}
Please feel free to click on my LinkedIn and GitHub links for more info! <br> [<i class="fa-brands fa-linkedin"></i> Linkedin](https://www.linkedin.com/in/yanglu97/)  \|  [<i class="fa-brands fa-github"></i> GitHub](https://github.com/Roxy-97)
:::

## Audrey Tan

My name is Audrey, and I am currently pursuing a Master's degree at Singapore Management University, specializing in the Data Science & Analytics track. As part of the Visual Analytics and Applications course, I had the opportunity to apply my knowledge in R, Shiny, and Quarto to derive insights and solve problems through data visualization. These tools have proven to be highly valuable and practical for real-world applications. I am also deeply grateful to my project team. Working with them has been an enriching experience, and I have learned a great deal throughout the course.

::: {.callout-note title="Audrey"}
Please feel free to click on my LinkedIn and GitHub links for more info! <br> [<i class="fa-brands fa-github"></i> GitHub](https://github.com/dreytwy)
:::

## Li Jianyi

My name is Jianyi, and I came into the Visual Analytics module hoping to learn how to turn complex data into clear and engaging visuals. The module exceeded my expectations by equipping me with practical skills in R, Shiny, and Quarto, while also teaching me the importance of design, storytelling, and user experience in data communication. I especially enjoyed building interactive dashboards and applying visual thinking to real-world scenarios. I believe these skills will be valuable in future projects, business reporting, and communicating insights to both technical and non-technical audiences.

::: {.callout-note title="Jianyi"}
Please feel free to click on my LinkedIn and GitHub links for more info! <br> [<i class="fa-brands fa-linkedin"></i> Linkedin](www.linkedin.com/in/jianyi-li-272017249)  \|  [<i class="fa-brands fa-github"></i> GitHub](https://github.com/JianyiLii)
:::
::::::
